package com.algotrader.bot.strategy;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Immutable value object representing a trading signal generated by a strategy.
 * 
 * Contains all information needed to execute a trade:
 * - Signal type (BUY, SELL, HOLD)
 * - Entry price and risk management levels (stop-loss, take-profit)
 * - Signal strength for filtering weak signals
 * - Reason for transparency and debugging
 * 
 * Used by trading strategies to communicate trade recommendations to the execution layer.
 */
public final class TradeSignal {
    
    private final SignalType signalType;
    private final String symbol;
    private final BigDecimal entryPrice;
    private final BigDecimal stopLossPrice;
    private final BigDecimal takeProfitPrice;
    private final double signalStrength;
    private final Instant timestamp;
    private final String reason;
    
    /**
     * Creates a new TradeSignal instance.
     * 
     * @param signalType the type of signal (BUY, SELL, HOLD)
     * @param symbol the trading symbol (e.g., "BTC/USDT")
     * @param entryPrice the recommended entry price
     * @param stopLossPrice the stop-loss price for risk management
     * @param takeProfitPrice the take-profit price target
     * @param signalStrength the strength of the signal (0.0-1.0)
     * @param timestamp the time when this signal was generated
     * @param reason the reason for this signal (for logging/debugging)
     * @throws IllegalArgumentException if any parameter is null or invalid
     */
    public TradeSignal(SignalType signalType, String symbol, BigDecimal entryPrice,
                       BigDecimal stopLossPrice, BigDecimal takeProfitPrice,
                       double signalStrength, Instant timestamp, String reason) {
        if (signalType == null || symbol == null || entryPrice == null ||
            stopLossPrice == null || takeProfitPrice == null || 
            timestamp == null || reason == null) {
            throw new IllegalArgumentException("All parameters must be non-null");
        }
        
        if (symbol.trim().isEmpty()) {
            throw new IllegalArgumentException("Symbol cannot be empty");
        }
        
        if (signalStrength < 0.0 || signalStrength > 1.0) {
            throw new IllegalArgumentException("Signal strength must be between 0.0 and 1.0");
        }
        
        if (entryPrice.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Entry price must be positive");
        }
        
        if (stopLossPrice.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Stop-loss price must be positive");
        }
        
        if (takeProfitPrice.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Take-profit price must be positive");
        }
        
        this.signalType = signalType;
        this.symbol = symbol;
        this.entryPrice = entryPrice;
        this.stopLossPrice = stopLossPrice;
        this.takeProfitPrice = takeProfitPrice;
        this.signalStrength = signalStrength;
        this.timestamp = timestamp;
        this.reason = reason;
    }
    
    public SignalType getSignalType() {
        return signalType;
    }
    
    public String getSymbol() {
        return symbol;
    }
    
    public BigDecimal getEntryPrice() {
        return entryPrice;
    }
    
    public BigDecimal getStopLossPrice() {
        return stopLossPrice;
    }
    
    public BigDecimal getTakeProfitPrice() {
        return takeProfitPrice;
    }
    
    public double getSignalStrength() {
        return signalStrength;
    }
    
    public Instant getTimestamp() {
        return timestamp;
    }
    
    public String getReason() {
        return reason;
    }
    
    @Override
    public String toString() {
        return "TradeSignal{" +
                "signalType=" + signalType +
                ", symbol='" + symbol + '\'' +
                ", entryPrice=" + entryPrice +
                ", stopLossPrice=" + stopLossPrice +
                ", takeProfitPrice=" + takeProfitPrice +
                ", signalStrength=" + signalStrength +
                ", timestamp=" + timestamp +
                ", reason='" + reason + '\'' +
                '}';
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        
        TradeSignal that = (TradeSignal) o;
        
        if (Double.compare(that.signalStrength, signalStrength) != 0) return false;
        if (signalType != that.signalType) return false;
        if (!symbol.equals(that.symbol)) return false;
        if (!entryPrice.equals(that.entryPrice)) return false;
        if (!stopLossPrice.equals(that.stopLossPrice)) return false;
        if (!takeProfitPrice.equals(that.takeProfitPrice)) return false;
        if (!timestamp.equals(that.timestamp)) return false;
        return reason.equals(that.reason);
    }
    
    @Override
    public int hashCode() {
        int result;
        long temp;
        result = signalType.hashCode();
        result = 31 * result + symbol.hashCode();
        result = 31 * result + entryPrice.hashCode();
        result = 31 * result + stopLossPrice.hashCode();
        result = 31 * result + takeProfitPrice.hashCode();
        temp = Double.doubleToLongBits(signalStrength);
        result = 31 * result + (int) (temp ^ (temp >>> 32));
        result = 31 * result + timestamp.hashCode();
        result = 31 * result + reason.hashCode();
        return result;
    }
}
