package com.algotrader.bot.backtest.api.response;

import com.algotrader.bot.shared.api.response.AsyncTaskMonitorResponse;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import com.algotrader.bot.validation.ValidationStatus;

public record BacktestSummaryResponse(
    Long id,
    String strategyId,
    Long datasetId,
    String datasetName,
    String experimentName,
    String experimentKey,
    String datasetChecksumSha256,
    String datasetSchemaVersion,
    LocalDateTime datasetUploadedAt,
    Boolean datasetArchived,
    String symbol,
    String timeframe,
    String executionStatus,
    String validationStatus,
    BigDecimal initialBalance,
    BigDecimal finalBalance,
    BigDecimal netProfit,
    BigDecimal sharpeRatio,
    BigDecimal profitFactor,
    BigDecimal winRate,
    BigDecimal maxDrawdown,
    Integer totalTrades,
    Integer winningTrades,
    Integer losingTrades,
    Integer feesBps,
    Integer slippageBps,
    LocalDateTime startDate,
    LocalDateTime endDate,
    LocalDateTime timestamp,
    String executionStage,
    Integer progressPercent,
    Integer processedCandles,
    Integer totalCandles,
    LocalDateTime currentDataTimestamp,
    String statusMessage,
    LocalDateTime lastProgressAt,
    LocalDateTime startedAt,
    LocalDateTime completedAt,
    String errorMessage,
    List<BacktestStrategyMetricResponse> strategyMetrics,
    AsyncTaskMonitorResponse asyncMonitor
) {}
